stages:
  load_data:
    cmd : python refactoring/data/load_data.py --data_path data/raw/ObesityDataSet_raw_and_data_sinthetic.csv --output_dir data/processed --params params.yaml
    deps:
    - data/raw/ObesityDataSet_raw_and_data_sinthetic.csv
    - refactoring/data/load_data.py
    outs:
    - data/processed/data.csv
    params:
    - version
    - data_adjusted
  prepare_data:
    cmd: python refactoring/preprocessing/data_preparation.py --data_path data/processed/data.csv --output_dir data/processed --params params.yaml
    deps:
    - data/processed/data.csv
    - refactoring/preprocessing/data_preparation.py
    - params.yaml
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/X_val.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/y_val.csv
    params:
     - split_options
     - features
     - version
  train_model:
    cmd : python refactoring/modeling/train.py --X_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --params params.yaml
    deps:
    - refactoring/modeling/train.py
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - params.yaml
    outs :
    - models/best_model.pkl
    params:
    - models
    - mlflow
    - version
  test_model:
    cmd : python refactoring/evaluation/evaluate.py --X_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --params params.yaml --model_path models/best_model.pkl
    deps:
    - refactoring/evaluation/evaluate.py
    - data/processed/X_test.csv
    - data/processed/y_test.csv
    - params.yaml
    - models/best_model.pkl
    outs:
    - metrics/evaluation.json
    - data/predictions/predictions.csv
    params:
    - version
    - mlflow
  test_run:
    cmd: pytest --html=reports/tests/report.html
    outs:
    - reports/tests/report.html