stages:
  load_data:
    cmd: python refactoring/preprocessing/data_preparation.py --data_path data/raw/ObesityDataSet_raw_and_data_sinthetic.csv --output_dir data/processed --params params.yaml
    deps:
    - data/raw/ObesityDataSet_raw_and_data_sinthetic.csv
    - refactoring/preprocessing/data_preparation.py
    - params.yaml
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/X_val.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/y_val.csv
    params:
     - data_adjusted
     - split_options
     - features