data:
  filepath: data/raw/ObesityDataSet_raw_and_data_sinthetic.csv
  preprocessed: data/processed
  models: models/

data_adjusted:
  round_decimals: {'Height' : 2, 'Weight' : 0, 'CH2O' : 0}
  float_to_int : ['Weight', 'Age', 'FCVC', 'NCP', 'FAF', 'TUE', 'CH2O']
  int_to_str : ['FCVC', 'NCP', 'FAF', 'TUE', 'CH2O']

split_options:
  test_size : 0.2
  val_size : 0.1
  random_state: 1

features:
  ordinal: ['FCVC', 'NCP', 'CH2O', 'FAF', 'TUE', 'CALC']
  categorical: ['Gender', 'family_history_with_overweight', 'FAVC', 'CAEC', 'SMOKE', 'SCC', 'MTRANS']
  numerical: ['Height', 'Weight']
  other: ['Age']
  target: 'NObeyesdad'

model_global_options:
  model_random_state : 1
  
models:
  gradient_boosting:
    learnig_rate: [0.01, 0.1, 0.2]
    max_depth: [3, 5, 7]
    n_estimators: [100, 200]
    random_state : 1
  logistic_regession:
    multi_class : 'multinomial'
    solver : ['lbfgs', 'saga']
    max_iter : 1000
    random_state : 1
    C: [0.1, 1, 10, 100]
  svm :
    probability : True
    random_state : 1
    C: [0.1, 1, 10]
    kernel: ['linear', 'rbf']
    gamma: [1, 0.1, 0.01]
  random_forest :
    random_state : 1
    n_estimators : [100, 200, 300]
    max_depth : [10, 20, 30, None]
    min_samples_split : [2, 5, 10]
    min_samples_leaf : [1, 2, 4]
  k_neighbors :
    n_neighbors: [3, 5, 7, 9]
    weights: ['uniform', 'distance']
    p: [1, 2]



mlflow:
  experiment_name: "Obesity Level Analysis V1"
  tracking_uri: "http://localhost:5000"